In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
# print("hello world")
data = pd.read_csv("extracted_files/mnist_train.csv")

In [3]:
data.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      5    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      4    0    0    0    0    0    0    0    0    0  ...      0      0   
3      1    0    0    0    0    0    0    0    0    0  ...      0      0   
4      9    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [4]:
data  = np.array(data)
m,n = data.shape
np.random.shuffle(data)

data_dev = data[0:1000].T
y_dev = data_dev[0]
x_dev = data_dev[1:n]
x_dev = x_dev/255.0

data_train = data[1000:m].T
y_train = data_train[0]
x_train = data_train[1:n]
x_train = x_train/255.0
_,m_train = x_train.shape

In [5]:
# x_train[:,0].shape
y_train

array([9, 3, 8, ..., 6, 8, 2], dtype=int64)

In [6]:
# import numpy as np

# class CustomScratchNeuralNetwork:
#     def __init__(self):
#         pass

#     def init_params(self):
#         self.W1 = np.random.rand(10, 784) - 0.5
#         self.b1 = np.random.rand(10, 1) - 0.5
#         self.W2 = np.random.rand(10, 10) - 0.5
#         self.b2 = np.random.rand(10, 1) - 0.5

#     def relu(self, Z):
#         return np.maximum(0, Z)

#     def softmax(self, Z):
#         return np.exp(Z) / np.sum(np.exp(Z))

#     def forward_prop(self, X):
#         self.Z1 = self.W1.dot(X) + self.b1
#         self.A1 = self.relu(self.Z1)
#         self.Z2 = self.W2.dot(self.A1) + self.b2
#         self.A2 = self.softmax(self.Z2)

#     def one_hot(self, Y):
#         one_hot_Y = np.zeros((Y.size, Y.max() + 1))
#         one_hot_Y[np.arange(Y.size), Y] = 1
#         one_hot_Y = one_hot_Y.T
#         return one_hot_Y

#     def deriv_relu(self, Z):
#         return Z > 0

#     def back_prop(self, X, Y):
#         one_hot_Y = self.one_hot(Y)
#         dL_Z2 = 2 * (self.A2 - one_hot_Y)
#         dL_W2 = 1 / X.shape[1] * dL_Z2.dot(self.A1.T)
#         dL_b2 = 1 / X.shape[1] * np.sum(dL_Z2)

#         dL_Z1 = self.W2.T.dot(dL_Z2) * self.deriv_relu(self.Z1)
#         dL_W1 = 1 / X.shape[1] * dL_Z1.dot(X.T)
#         dL_b1 = 1 / X.shape[1] * np.sum(dL_Z1)

#         return dL_W1, dL_b1, dL_W2, dL_b2

#     def update_params(self, alpha):
#         self.W1 = self.W1 - alpha * self.dL_W1
#         self.b1 = self.b1 - alpha * self.dL_b1
#         self.W2 = self.W2 - alpha * self.dL_W2
#         self.b2 = self.b2 - alpha * self.dL_b2

#     def get_predicts(self):
#         return np.argmax(self.A2, 0)

#     def get_accuracy(self, Y):
#         return np.sum(self.get_predicts() == Y) / Y.size

#     def gradient_descent(self, X, Y, iters, alpha):
#         self.init_params()
#         for i in range(iters):
#             self.forward_prop(X)
#             self.dL_W1, self.dL_b1, self.dL_W2, self.dL_b2 = self.back_prop(X, Y)
#             self.update_params(alpha)
#             if i % 10 == 0:
#                 print("Iteration: ", i)
#                 print("Accuracy: ", self.get_accuracy(Y))

#         return self.W1, self.b1, self.W2, self.b2


In [7]:
def init_params():
    W1 = np.random.rand(32, 784) - 0.5
    b1 = np.random.rand(32, 1) - 0.5

    W2 = np.random.rand(32, 32) - 0.5
    b2 = np.random.rand(32, 1) - 0.5

    W3 = np.random.rand(32, 32) - 0.5
    b3 = np.random.rand(32, 1) - 0.5

    W4 = np.random.rand(32, 32) - 0.5
    b4 = np.random.rand(32, 1) - 0.5

    W5 = np.random.rand(10, 32) - 0.5
    b5 = np.random.rand(10, 1) - 0.5

    return W1, b1, W2, b2, W3, b3, W4, b4, W5, b5

def Relu(Z):
    return np.maximum(0,Z)  

def Softmax(Z):
    return np.exp(Z)/sum(np.exp(Z))

def forward_prop(W1, b1, W2, b2, W3, b3, W4, b4, W5, b5, X):
    Z1 = W1.dot(X) + b1
    A1 = Relu(Z1)

    Z2 = W2.dot(A1) + b2
    A2 = Relu(Z2)

    Z3 = W3.dot(A2) + b3
    A3 = Relu(Z3)

    Z4 = W4.dot(A3) + b4
    A4 = Relu(Z4)

    Z5 = W5.dot(A4) + b5
    A5 = Softmax(Z5)

    return Z1, A1, Z2, A2, Z3, A3, Z4, A4, Z5, A5

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max()+1))
    one_hot_Y[np.arange(Y.size),Y] =1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def deriv_relu(Z):
    return Z>0

def back_prop(Z1, A1, Z2, A2, Z3, A3, Z4, A4, Z5, A5, W2, W3, W4, W5, X, Y):
    one_hot_Y = one_hot(Y)

    dL_Z5 = A5 - one_hot_Y
    dL_W5 = 1/m * dL_Z5.dot(A4.T)
    dL_b5 = 1/m * np.sum(dL_Z5)

    dL_Z4 = W5.T.dot(dL_Z5) * deriv_relu(Z4)
    dL_W4 = 1/m * dL_Z4.dot(A3.T)
    dL_b4 = 1/m * np.sum(dL_Z4)

    dL_Z3 = W4.T.dot(dL_Z4) * deriv_relu(Z3)
    dL_W3 = 1/m * dL_Z3.dot(A2.T)
    dL_b3 = 1/m * np.sum(dL_Z3)

    dL_Z2 = W3.T.dot(dL_Z3) * deriv_relu(Z2)
    dL_W2 = 1/m * dL_Z2.dot(A1.T)
    dL_b2 = 1/m * np.sum(dL_Z2)

    dL_Z1 = W2.T.dot(dL_Z2) * deriv_relu(Z1)
    dL_W1 = 1/m * dL_Z1.dot(X.T)
    dL_b1 = 1/m * np.sum(dL_Z1)

    return dL_W1, dL_b1, dL_W2, dL_b2, dL_W3, dL_b3, dL_W4, dL_b4, dL_W5, dL_b5

def update_params(W1, b1, W2, b2, W3, b3, W4, b4, W5, b5, dL_W1, dL_b1, dL_W2, dL_b2, dL_W3, dL_b3, dL_W4, dL_b4, dL_W5, dL_b5, alpha):
    W1 = W1 - alpha * dL_W1
    b1 = b1 -  alpha * dL_b1
    W2 = W2 - alpha * dL_W2
    b2 = b2 -  alpha * dL_b2
    W3 = W3 - alpha * dL_W3
    b3 = b3 -  alpha * dL_b3
    W4 = W4 - alpha * dL_W4
    b4 = b4 -  alpha * dL_b4
    W5 = W5 - alpha * dL_W5
    b5 = b5 -  alpha * dL_b5
    return W1, b1, W2, b2, W3, b3, W4, b4, W5, b5


In [8]:
# def init_params():
#     W1 = np.random.rand(10,784) - 0.5
#     b1 = np.random.rand(10,1) - 0.5

#     W2 = np.random.rand(10,10) - 0.5
#     b2 = np.random.rand(10,1) - 0.5
#     return W1,b1,W2,b2

# def Relu(Z):
#     return np.maximum(0,Z)  

# def Softmax(Z):
#     return np.exp(Z)/sum(np.exp(Z))

# def forward_prop(W1,b1,W2,b2,X):
#     Z1 = W1.dot(X)+b1
#     A1 = Relu(Z1)

#     Z2 = W2.dot(A1) + b2
#     A2 = Softmax(Z2)
#     return Z1,A1,Z2,A2

# def one_hot(Y):
#     one_hot_Y = np.zeros((Y.size, Y.max()+1))
#     one_hot_Y[np.arange(Y.size),Y] =1
#     one_hot_Y = one_hot_Y.T
#     return one_hot_Y

# def deriv_relu(Z):
#     return Z>0

# def back_prop(Z1, A1, Z2, A2, W2, X, Y):
#      one_hot_Y = one_hot(Y)
#      dL_Z2 = 2 * (A2 - one_hot_Y)
#      dL_W2 = 1/m * dL_Z2.dot(A1.T)
#      dL_b2 = 1/m * np.sum(dL_Z2)
    
#      dL_Z1 = W2.T.dot(dL_Z2) * deriv_relu(Z1)
#      dL_W1 = 1/m * dL_Z1.dot(X.T)
#      dL_b1 = 1/m * np.sum(dL_Z1)
#      return dL_W1, dL_b1, dL_W2, dL_b2

# def update_params(W1, b1, W2, b2, dL_W1, dL_b1, dL_W2, dL_b2, alpha):
#     W1 = W1 - alpha * dL_W1
#     b1 = b1 -  alpha * dL_b1
#     W2 = W2 - alpha * dL_W2
#     b2 = b2 -  alpha * dL_b2
#     return W1, b1, W2, b2

In [9]:
def get_predicts(A2):
    return np.argmax(A2,0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions==Y) / Y.size

def gradient_descent(X,Y, iters, alpha):
    W1, b1, W2, b2, W3, b3, W4, b4, W5, b5 = init_params()
    for i in range(iters):
        Z1, A1, Z2, A2, Z3, A3, Z4, A4, Z5, A5 = forward_prop(W1, b1, W2, b2, W3, b3, W4, b4, W5, b5, X)
        dL_W1, dL_b1, dL_W2, dL_b2, dL_W3, dL_b3, dL_W4, dL_b4, dL_W5, dL_b5 = back_prop(Z1, A1, Z2, A2, Z3, A3, Z4, A4, Z5, A5, W2, W3, W4, W5, X, Y)
        W1, b1, W2, b2, W3, b3, W4, b4, W5, b5 = update_params(W1, b1, W2, b2, W3, b3, W4, b4, W5, b5, dL_W1, dL_b1, dL_W2, dL_b2, dL_W3, dL_b3, dL_W4, dL_b4, dL_W5, dL_b5, alpha)
        if(i%10==0):
            print("Interation: ", i)
            print("Accuracy: ", get_accuracy(get_predicts(A2), Y))
    return W1, b1, W2, b2, W3, b3, W4, b4, W5, b5

In [12]:
# object = CustomScratchNeuralNetwork()
W1, b1, W2, b2, W3, b3, W4, b4, W5, b5 = gradient_descent(x_train, y_train, 5000, 0.03)

Interation:  0
[13  8 14 ... 16  4  4] [9 3 8 ... 6 8 2]
Accuracy:  0.04938983050847458
Interation:  10
[13  8 14 ... 11  4  4] [9 3 8 ... 6 8 2]
Accuracy:  0.04867796610169491
Interation:  20
[13  8 14 ... 11  4  4] [9 3 8 ... 6 8 2]
Accuracy:  0.05147457627118644
Interation:  30
[13  8 14 ... 11  4  4] [9 3 8 ... 6 8 2]
Accuracy:  0.05386440677966102
Interation:  40
[13  8 14 ... 11  4  4] [9 3 8 ... 6 8 2]
Accuracy:  0.05511864406779661
Interation:  50
[13  8 14 ... 11  4  4] [9 3 8 ... 6 8 2]
Accuracy:  0.056101694915254234
Interation:  60
[13  8 14 ... 11  4  4] [9 3 8 ... 6 8 2]
Accuracy:  0.056745762711864406
Interation:  70
[13  8 14 ... 11  4  4] [9 3 8 ... 6 8 2]
Accuracy:  0.05723728813559322
Interation:  80
[13  8 14 ... 11  4  4] [9 3 8 ... 6 8 2]
Accuracy:  0.058322033898305085
Interation:  90
[13  8 14 ... 11  4  4] [9 3 8 ... 6 8 2]
Accuracy:  0.059322033898305086
Interation:  100
[13 13 14 ... 16  4  4] [9 3 8 ... 6 8 2]
Accuracy:  0.06023728813559322
Interation:  110


KeyboardInterrupt: 

In [ ]:
def make_predictions(X, W1, b1, W2, b2):
    _,_,_,A2 = forward_prop(W1, b1, W2, b2, X)
    preds = get_predicts(A2)
    return preds

In [ ]:
dev_preds = make_predictions(x_dev, W1, b1, W2, b2)
get_accuracy(dev_preds, y_dev)

TypeError: forward_prop() missing 6 required positional arguments: 'b3', 'W4', 'b4', 'W5', 'b5', and 'X'